Project 2(elderly wearable webpage)
Redback-Operations/redback-senior-web pull request #4
Opened 2024-05-12 18:40 UTC by aaryanbansal

2024-05-13 01:17 UTC, doubleedesign requested changes
- Please refactor to work with React.
- All code needs to be in the existing React app in the `src` folder. Please do not add a new React app or any other new folders other than those required to create your routes and components.

Please see the [guides](https://redback-operations.github.io/redback-documentation/docs/category/front-end-web-development) on the company documentation website for more information.

2024-05-14 23:30 UTC, doubleedesign requested changes
Please update to follow current React standards and the existing file structure and naming conventions in the app. You can find step-by-step instructions on how to do much of this in the company documentation website. In particular:
- [Pages and Routes](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/new-routes)
- [Creating components](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/new-components)
- [Using Styled Components](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/styled-components)

2024-05-14 23:30 UTC, doubleedesign commented on src/html/ExploreFeature.js
> +class ExploreFeatures extends React.Component {
Please use function components, as class components are deprecated. [Here's some more information](https://react.dev/reference/react/Component) including how to migrate.

2024-05-14 23:30 UTC, doubleedesign commented on src/html/contact.html
> +<!DOCTYPE html>
Please refactor all HTML in to React components. There should not be any new `.html` files.

2024-05-14 23:30 UTC, doubleedesign commented on src/html/common.css
> +/* External CSS style file */
Please refactor all CSS into Styled Components. You can find some more information here: https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/styled-components

2024-07-01 13:11 UTC, ben-AI-cybersec commented
Tested locally. None of this code appears to work with the react app. Closing PR

2024-07-01 13:11 UTC, closed without merging